version: "3.9"

services:
  ubuntu1:
    image: ubuntu:22.04
    container_name: ubuntu1
    hostname: ubuntu1
    command: ["sleep", "infinity"]
    networks:
      lab-net:
        ipv4_address: 172.19.0.4
    volumes:
      - C:/ubuntu-data:/mnt/data

networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
