// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"s3-poc/config"
	"s3-poc/data"
	"s3-poc/handlers"
	"s3-poc/services"
)

// Injectors from wire.go:

func InitializeUserHandler() (*handlers.UserHandler, error) {
	db, err := config.ConnectDB()
	if err != nil {
		return nil, err
	}
	userRepository := data.NewUserRepository(db)
	client, err := config.NewS3Client()
	if err != nil {
		return nil, err
	}
	s3Repository := data.NewS3Repository(client)
	userService := services.NewUserService(userRepository, s3Repository)
	userHandler := handlers.NewUserHandler(userService)
	return userHandler, nil
}

func InitializeS3Handler() (*handlers.S3Handler, error) {
	client, err := config.NewS3Client()
	if err != nil {
		return nil, err
	}
	s3Repository := data.NewS3Repository(client)
	s3Service := services.NewS3Service(s3Repository)
	s3Handler := handlers.NewS3Handler(s3Service)
	return s3Handler, nil
}
